name: 'build lib'
description: 'build library'
runs:
  using: "composite"
  steps:
    - run: npm ci
      working-directory: lib
    - run: npm run build --if-present
      working-directory: lib

    - name: Test
      run: npm run coverage
      working-directory: lib
