# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@cobreti'

      - name: build lib
        uses: ./.github/actions/build-lib

      - name: build testapp
        uses: ./.github/actions/build-testapp

